#!/usr/bin/env bash

#PBS -l walltime=1:00:00
#PBS -l nodes=1:ppn=2
#PBS -N rgvm
#PBS -M skulkarni@tgen.org
#PBS -m be
#PBS -t 1-24

CHRS=(DUMMY 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 X Y)
CHR=${CHRS[$PBS_ARRAYID]}
echo "Chromosome $CHR"

cd $PBS_O_WORKDIR

source ./setup.sh
module load yaml
module load samtools
module load htslib

export GVM_EXEC=$PWD/gvm

export SC="/scratch/skulkarni"
export PERL5LIB="$PERL5LIB:/home/rhalperin/perl5lib/lib"
export CONF=/home/skulkarni/programs/gvm/conf.yaml

export JOBNUM=$(cut -f1 -d. <<<$PBS_JOBID | sed 's:\[.\+\?\]::')

mkdir $SC/$JOBNUM

sed "s/\\\$OUTFILE/$JOBNUM\/out/g" $CONF > $SC/$JOBNUM/conf.yaml

touch $SC/$JOBNUM/still_running_chr$CHR
$GVM_EXEC $SC/$JOBNUM/conf.yaml $CHR
rm $SC/$JOBNUM/still_running_chr$CHR

